font_family FiraCode Nerd Font

window_padding_width 1
window_margin_width 2

allow_remote_control yes

foreground                      #00FF66
background                      #000000
selection_foreground            #99FFCC
selection_background            #66FF99
background_opacity 0.00001

#: Cursor colors

cursor                          #00FF66

#: URL underline color when overing with mouse

url_color                       #72a7bc

#: Tab bar colors


